server_routeros_config_users:
  - name: "{{ vault_routeros.user }}"
    password: "{{ vault_routeros.password }}"
    key: "{{ vault_routeros.key }}"
    group: full
local:
  config:
    management:
        interface: ether24
        data: "{{ networking.subnets.ipmi }}"
        address: "{{ addressing[inventory_hostname_short].address | ansible.utils.ipaddr('address') }}"
    ntp: "{{ services_vars.ntp | map(attribute='address') | map('ansible.utils.ipaddr', 'address') }}"
    interfaces:
      lag:
        - name: bond0
          comment: virt-01 bound
          members:
            - ether1
            - ether2
            - ether3
        - name: bond1
          comment: router-01 bound
          members:
            - ether4
            - ether5
            - ether6
        - name: bond2
          comment: virt-02 bound
          members:
          - ether9
          - ether10
      logical:
        - name: bond0
          frame_types: admit-only-vlan-tagged
          comment: virt-01
        - name: bond1
          frame_types: admit-only-vlan-tagged
          comment: router-01
        - name: bond2
          frame_types: admit-only-vlan-tagged
          comment: virt-02
        - name: ether11
          frame_types: admit-only-vlan-tagged
          comment: virt-04
        - name: ether16
          frame_types: admit-only-vlan-tagged
          comment: virt-03
        - name: ether7
          frame_types: admit-only-untagged-and-priority-tagged
          pvid: "{{ networking.subnets.ipmi.vid }}"
          comment: virt-01 IPMI
        - name: ether8
          frame_types: admit-only-untagged-and-priority-tagged
          pvid: "{{ networking.subnets.ipmi.vid }}"
          comment: virt-02 IPMI
        - name: ether14
          frame_types: admit-only-vlan-tagged
          comment: ap-01
          pvid: 4094
        - name: ether12
          frame_types: admit-only-untagged-and-priority-tagged
          pvid: "{{ networking.subnets.iot.vid }}"
          comment: Philips Hue Bound
        - name: ether24
          frame_types: admit-only-vlan-tagged
          comment: Management Interface
    vlans:
      - name: virt
        vid: "{{ networking.subnets['virt'].vid }}"
        interfaces: 
          tagged: &if001
            - bond0
            - bond1
            - bond2
            - ether7
            - ether11
            - ether16
            - ether24
      - name: servers
        vid: "{{ networking.subnets['srv'].vid }}"
        interfaces:
          tagged: *if001
      - name: mgt
        vid: "{{ networking.subnets['mgt'].vid }}"
        interfaces:
          tagged: *if001
      - name: ipmi
        vid: "{{ networking.subnets['ipmi'].vid }}"
        interfaces:
          tagged:
            - bridge
            - ether14
            - ether24
            - bond1
          untagged:
            - ether7
            - ether8
      - name: trust
        vid: "{{ networking.subnets['devices'].vid }}"
        interfaces:
          tagged: &if002
            - bond1
            - ether14
      - name: iot
        vid: "{{ networking.subnets['iot'].vid }}"
        interfaces:
          tagged:
            - bond1
            - ether14
            - ether16
          untagged:
            - ether12
