networking:
  hypervisor:
    network: 192.168.161.0/24
    vid: 161
    access:
      - services
    hosts:
      curse: 192.168.161.1/24
      impel: 192.168.161.2/24
      sacrilege: 192.168.161.3/24
      vengeance: 192.168.161.4/24
  ipmi:
    network: 192.168.183.0/24
    vid: 183
    hosts:
      palas: 192.168.183.2/24
  management:
    network: 192.168.177.0/24
    vid: 177
  trusted:
    network: 192.168.201.0/24
    vid: 201
    access:
      - services
      - wan
  services:
    network: 192.168.168.0/24
    vid: 168
    access:
      - wan
      - hypervisor
  wan:
    vid: 10
    network: 0.0.0.0/0
    access:
      - services
      - trusted

