- name: Handler - Restart the Kea Service
  ansible.builtin.systemd_service:
    name: isc-kea-dhcp4-server
    enabled: true
    state: restarted

- name: Handler - Restart the Kea DDNS Service
  ansible.builtin.systemd_service:
    name: isc-kea-dhcp-ddns-server
    enabled: true
    state: restarted
