- name: Handler - Restart Unbound
  ansible.builtin.systemd_service:
    name: unbound
    state: restarted

- name: Handler - Restart AdGuardHome
  ansible.builtin.systemd_service:
    name: AdGuardHome
    state: restarted
