- name: install_server_dns
  ansible.builtin.apt:
    cache_valid_time: "{{ apt.cache }}"
    name:
      - unbound

- name: template_server_dns_configuration
  ansible.builtin.template:
    src: unbound.conf.j2
    dest: /etc/unbound/unbound.conf
    mode: "644"
  notify: handler_service_restart_dns

- name: download_adguard
  delegate_to: localhost
  ansible.builtin.get_url:
    url: https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.107.52/AdGuardHome_linux_amd64.tar.gz
    checksum: sha256:a2645ecf23ccadbb0d97b324aef9bc67d126b8e394428ae5a23c2f1b73c5d140
    dest: /tmp/
    mode: "644"
  register: download_adguard_result

- name: unarchive_adguard
  ansible.builtin.unarchive:
    src: "{{ download_adguard_result.dest }}"
    remote_src: false
    dest: /opt/
    mode: "644"

- name: chmod_adguard
  ansible.builtin.file:
    mode: "744"
    path: /opt/AdGuardHome/AdGuardHome
    state: file

- name: template_adguard_configuration
  ansible.builtin.template:
    src: adguard.yml.j2
    dest: /opt/AdGuardHome/adguard.yml
    mode: "600"
  notify: handler_service_restart_adguard

- name: service_facts
  ansible.builtin.service_facts:
  register: service_facts_adguard_result

- name: command_adguard_installation
  when: service_facts_adguard_result.ansible_facts.services['AdGuardHome.service'] is undefined
  ansible.builtin.command:
    cmd: /opt/AdGuardHome/AdGuardHome -s install -c /opt/AdGuardHome/adguard.yml
  register: command_adguard_installation_result
  changed_when: command_adguard_installation_result.rc == 0

- name: install_certbot
  ansible.builtin.apt:
    cache_valid_time: "{{ apt.cache }}"
    name:
      - certbot
      - python3-certbot-dns-cloudflare
      - python3-certbot-dns-route53
      - python3-certbot-dns-digitalocean

- name: configure_certbot_credentials
  ansible.builtin.blockinfile:
    path: /etc/certbot.conf
    mode: 600
    create: true
    block: |
      {{ all_secrets.certbot.challenge.api.key }}={{ all_secrets.certbot.challenge.api.value }}

- name: verify_enabled_certificate
  ansible.builtin.stat:
    path: "/etc/letsencrypt/live/dns.{{ all_secrets.tld.internal }}"
  register: verify_enabled_certificate_result

- name: command_run_certbot
  when: verify_enabled_certificate.stat.exists is false
  ansible.builtin.command:
    cmd: "certbot certonly {{ all_secrets.certbot.parameters }}\
      -d dns.{{ all_secrets.tld.internal }}"
  register: command_run_certbot_result
  changed_when: command_run_certbot_result.rc == 0

- name: configure_certificate_renewal_hook
  ansible.builtin.blockinfile:
    path: /etc/letsencrypt/renewal-hooks/post/adguard-restart.sh
    mode: "774"
    create: true
    block: |
      #!/bin/bash
      systemctl restart AdGuardHome
