- name: hypervisor_playbook
  hosts: hypervisor
  gather_facts: false
  roles:
    - common
    - proxmox

- name: border_playbook
  hosts: border
  gather_facts: false
  roles:
    - vyos

- name: lxc_playbook
  hosts: lxc
  gather_facts: false
  roles:
    - lxc

- name: dhcp_playbook
  hosts: dhcp
  gather_facts: false
  roles:
    - lxc_debian
    - server_dhcp

- name: dns_playbook
  hosts: dns
  gather_facts: false
  roles:
    - lxc_debian
    - server_dns

- name: postgresql_playbook
  hosts: postgresql
  gather_facts: false
  roles:
    - lxc_debian
    - server_postgresql

- name: ns_playbook
  hosts: ns
  gather_facts: false
  roles:
    - lxc_debian
    - server_ns

- name: certificates_playbook
  hosts: certificates
  gather_facts: false
  roles:
    - lxc_debian
    - server_certbot

- name: nfs_playbook
  hosts: nfs
  gather_facts: false
  roles:
    - server_nfs
    - sshd
